[package]
name = "NAMHL"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version="4.5.54", features=["derive"] }
serde = { version="1.0.228", features=["derive"] }
serde_json = "1.0.149"
walkdir = "2.5.0"
zip = "7.1.0"
